main: pl.bagnolimited.goldenappleeffects.GoldenAppleEffectsPlugin
name: GoldenAppleEffectsPlugin

version: 1.0.0
description: Change golden apple effects easily

author: BagnoDevelopment
website: github.bagnolimited.pl